# Generated by Django 5.0.2 on 2025-12-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100, unique=True)),
                ('product_name', models.TextField()),
                ('category', models.TextField()),
                ('discounted_price', models.CharField(max_length=100)),
                ('about_product', models.TextField()),
                ('img_link', models.URLField(max_length=1000)),
            ],
        ),
    ]
