# Generated by Django 5.2.9 on 2026-01-04 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_cartitem_wishlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
